---
name: Apply K8S Manifests

on:
  workflow_dispatch:

jobs:
  kubernetes-apply:
    if: github.ref == 'refs/heads/master'
    name: Terraform Apply
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Set use_application_default_credentials to true
        run: gcloud config set container/use_application_default_credentials true

      - name: Configure GKE credentials
        run: |
          gcloud container clusters get-credentials \
            main-cluster \
            --zone europe-west4-b \
            --project ersms-460608

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f kubernetes/
